# Generated by Django 5.1.5 on 2025-02-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('haqida', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('tirik', models.BooleanField(default=False)),
                ('mamlakat', models.CharField(blank=True, max_length=300, null=True)),
                ('t_sana', models.DateField(blank=True, null=True)),
                ('kitob_soni', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=250)),
                ('yil', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.bolim')),
                ('muallif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.muallif')),
            ],
            options={
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
